# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Course.create(title: "Infant Massage and Lullabies", start_time: "10AM Mondays", age_group: 0, description: "Infant Massage and Lullabies, while nurturing parent-child relationship and bond, teaches the benefits of massage for young infants. Rodrigo Montes, a certified infant massage therapist, will lead parents through routines of age appropriate massage techniques, coupled with an introduction to lullabies designed to sooth infants in their earliest stages. This class will equip parents with skills to use in and beyond the classroom.")
Course.create(title: "Early Childhood Music", start_time: "11AM Saturdays", age_group: 3, description: "Early Childhood Music classes offer the opportunity to engage children and adults in age appropriate singing, movement and rhythm instruments as children discover the creative energy intrinsic to the arts. Classes are designed to support children’s development as they learn to feel and keep a steady beat, find their singing voices and discover the joy of sharing music with others in their community. The repertoire includes both traditional and original songs, chants, stories, finger plays and nursery rhymes. Classes also provide parents and caregivers with a variety of ideas and strategies to continue the exploration beyond classes.")
Course.create(title: "Dance Basics", start_time: "10AM Saturdays", age_group: 5, description: "A fun, upbeat introduction to dance class drawing from the ballet, jazz and modern traditions. This structured class consists of a warm-up, stretch, across the floor combinations and center choreography. Establishes proper technique and alignment, builds dance vocabulary and encourages style, creativity and self-expression. This class, for children ages 4 and 5, is for students only without parents.")
